jms_serializer:
    visitors:
        xml_serialization:
            format_output: '%kernel.debug%'

    metadata:

        auto_detection: false
        directories:

            RestResource:
                namespace_prefix: "AuditorFramework\\Common\\Types\\Infrastructure\\Ui\\Http\\Rest\\Resource"
                path: '%kernel.project_dir%/src/Common/Types/Infrastructure/Ui/Http/Rest/ResourceRender/JmsSerializer/Annotation'
