oauth2:
  resource: '@TrikoderOAuth2Bundle/Resources/config/routes.xml'

user_controller:
  prefix: /api/security_and_acl/user
  resource: TheCodeFighters\Bundle\AuditorFramework\Common\Module\SecurityAndAcl\Infrastructure\Ui\Http\Rest\Controller\UserController

csv_controller:
  prefix: /api/common/csv
  resource: TheCodeFighters\Bundle\AuditorFramework\Common\Types\Infrastructure\Ui\Http\Rest\Controller\CsvController

#HealthCheckController
health_check_controller:
  prefix: /api/healthcheck
  resource: TheCodeFighters\Bundle\AuditorFramework\Common\Types\Infrastructure\Ui\Http\Rest\Controller\HealthCheckController
