services:
  AuditorFramework\Common\Types\Infrastructure\Ui\Http\Rest\Controller\Controller:
    abstract: true
    public: true
    autowire: true
    arguments:
      $commandBus: '@AuditorFramework\Common\Types\Application\CommandBus'
      $queryBus: '@AuditorFramework\Common\Types\Application\QueryBus'
      $identifiableDtoResourceToApiRestResourceDataTransformer: '@AuditorFramework\Common\Types\Infrastructure\Ui\Http\Rest\DataTransformer\IdentifiableDtoResourceToRestResourceDataTransformer'
      $nonIdentifiableDtoResourceToApiRestResourceDataTransformer: '@AuditorFramework\Common\Types\Infrastructure\Ui\Http\Rest\DataTransformer\NonIdentifiableDtoResourceToRestResourceDataTransformer'
      $serializer: '@jms_serializer'

  #ApiGateway Controllers
  AuditorFramework\Common\Types\Infrastructure\Ui\Http\ApiGateway\ApiGatewayController:
    parent: AuditorFramework\Common\Types\Infrastructure\Ui\Http\Rest\Controller\Controller
    abstract: true
    arguments:
      $clientDirector: '@AuditorFramework\Common\Types\Infrastructure\Ui\Http\Client\Oauth2ClientDirector'
      $clientBuilder: '@AuditorFramework\Common\Types\Infrastructure\Ui\Http\Client\Oauth2WithPasswordCredentialsClientBuilder'

  #HealthCheckController
  AuditorFramework\Common\Types\Infrastructure\Ui\Http\Rest\Controller\HealthCheckController:

  AuditorFramework\Common\Types\Infrastructure\Ui\Http\Rest\Controller\CsvController:
    parent: AuditorFramework\Common\Types\Infrastructure\Ui\Http\Rest\Controller\Controller
