AuditorFramework\Common\Types\Infrastructure\Ui\Http\Rest\Resource\IdentifiableRestResourceCollection:
    exclusion_policy: ALL
    properties:
      data:
        serialized_name: data
        type: array<AuditorFramework\Common\Types\Infrastructure\Ui\Http\Rest\Resource\IdentifiableRestResource>
        expose: true
